FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3001

CMD sh -c 'echo "Waiting for database to be ready..." && sleep 3 && (npm run migration:run || echo "Migration failed or already applied") && npm run start:dev'
